version: '3.7'
services:
  mysql_db:
    container_name: hba_db
    image: mysql:latest
    restart: always
    env_file:
      - database/mysql.env
    ports:
      -  3306:3306
    volumes:
      - ./database/dump-data:/var/lib/mysql
      - ./database/sql-scripts:/docker-entrypoint-initdb.d
  adminer_container:
    container_name: hba_db_adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
      ADMINER_DESIGN: galkaev
    ports:
      - 8090:8080
volumes:
  mysql_db_data: